version: "3.8"
services:
  client:
    image: node:20.0.0-alpine
    user: node
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8000:8000
    volumes:
      - ./front:/home/node